version: '3.8'

networks:
  devops-network:
    driver: bridge

volumes:
  jenkins_home:
  postgres_data:

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/mrgolbez/IdeaProjects/calculator-app/jenkins-kubeconfig:/root/.kube/config
      - ~/.minikube:/root/.minikube
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true
      - KUBECONFIG=/root/.kube/config  # Set environment variable for kubectl to pick up the kubeconfig file
    networks:
      - devops-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    depends_on:
      - db
    networks:
      - devops-network

  db:
    image: postgres:12
    container_name: postgres-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devops-network
