apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator-java8
          image: mrgolbez/calculator-java8:latest
          ports:
            - containerPort: 8081
        - name: calculator-java11
          image: mrgolbez/calculator-java11:latest
          ports:
            - containerPort: 8082
        - name: calculator-java17
          image: mrgolbez/calculator-java17:latest
          ports:
            - containerPort: 8083
