apiVersion: v1
kind: Service
metadata:
  name: calculator-java8-service
spec:
  selector:
    app: calculator
  ports:
    - name: java8
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-java11-service
spec:
  selector:
    app: calculator
  ports:
    - name: java11
      protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-java17-service
spec:
  selector:
    app: calculator
  ports:
    - name: java17
      protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort
